### ISSUE TITLE
CSV Import Issues

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/import#6]
- [ ] Example CSV doesn't work on live
- [ ] Section is required so if we don't have one, add a warning for that row?

**Comment by mauromsl** [comment]
It seems like the link does work https://iscore.iastatedigitalpress.com/plugins/imports/example_csv/

I've updated the instructions and example CSV to include the section name column in https://github.com/BirkbeckCTP/import/pull/5
